In [1]:
import numpy as np

In [21]:
observed = ['hot', 'cold']
latent = ['e1', 'e2', 'e3']

transition = np.array([
    [0.7, 0.3],
    [0.4, 0.6],
])
emission = np.array([
    [0.1, 0.4, 0.5],
    [0.7, 0.2, 0.1],
])
initial = np.array([
    [0.6, 0.4]
])

In [45]:
np.sum(initial.T * transition * emission[:, 1], axis=0)

array([0.232, 0.084])

In [49]:
def forward_one(obs, initial = initial):
    return np.sum(initial.T * transition * emission[:, obs], axis=0)

In [53]:
forward_one(2, forward_one(1))

array([0.1276 , 0.00756])

In [72]:
new_initial = forward_one(1)
new_initial

array([0.232, 0.084])

In [78]:
new_initial * transition.T * emission[:, 2]

array([[0.0812 , 0.00336],
       [0.0348 , 0.00504]])

In [69]:
print(0.232*.7*.5)
print(0.084*.4*.5)

0.0812
0.016800000000000002


In [64]:
print(0.232*0.3*0.1)
print(0.084*0.6*0.1)

0.00504
0.00696
